[server]
maxUploadSize = 200  # Taille max des fichiers upload√©s (MB)

[theme]
primaryColor = "#0E4A7A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"